### PR TITLE
Data for ACE1pack tests

### PR DESCRIPTION
**Pull request by gelzinyte**
- Small (33 configs) titanium-aluminium dataset to fit to. 
- Files associated with tests
  - expected fit errors (json)
  - ace_fit parameter files (json, yaml)

### CODE REVIEW

**Comment by cortner** [comment]
ok to merge this?

**Comment by cortner** [comment]
@gelzinyte Should we start by wrapping this up? How do you feel about actually splitting off an `ACE1data.jl`?

**Comment by gelzinyte** [comment]
Sorry I've missed this comment! 

In my mind, ACEData is just a place to store all the tarballs, so why to make it a Julia repository? 

To access these data via artefacts, the code downloads tarballs from links directly, the repository is not a dependency of the package that is using the artefacts. From artefacts' point of view, the artefacts could be stored under any link, it doesn't have to do anything with git. (Although the artefacts' tarballs are often stored in the same repository as the code using them, but in ACE case I think that doesn't make sense, because multiple repositories might wish to access the same files, for example xyzs for fitting)

**Comment by cortner** [comment]
you are right it should not be a Julia repo, the question was simply whether to rename it to something specific to ACE1. and you are also right there is no really strong reason to do this. I'll merge now.

**Pull request merged**
